package com.bruno.bookmanager.model;

public enum Genere {
    BIOGRAFIA, AUTOBIOGRAFIA, ROMANZO, ROMANZO_STORICO, GIALLO, THRILLER, AZIONE, FANTASCIENZA, DISTOPIA, FANTASY, HORROR, ROSA, UMORISTICO
}
